name: Gradle publish

on:
  workflow_call:


jobs:
  gradle-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check the calling organization
        if: ${{ github.repository_owner != 'cloudshiftinc' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('This reusable workflow can only be used by CloudShift.')

      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.DEVTOOLS_ROLE_ARN }}

      # set fetch-depth to get all history (incl. tags), as tags are used for versioning
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set JAVA_HOME
        id: JAVA_HOME
        run: |
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV

      - name: Setup and execute Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true
          gradle-home-cache-includes: |
            jdks
            go
            go-pkg-cache
          gradle-home-cache-excludes: |
            go/cache
          arguments: build check publish --info --stacktrace --no-configuration-cache
