name: Gradle publish

on:
  workflow_call:

jobs:
  gradle-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check the calling organization
        if: ${{ github.repository_owner != 'cloudshiftinc' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('This reusable workflow can only be used by CloudShift.')

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.DEVTOOLS_ROLE_ARN }}

      # set fetch-depth to get all history (incl. tags), as tags are used for versioning
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          # Install Java 11 to support Kotlin 1.5 / Gradle 7.4.x; remove once on Gradle 7.5
          java-version: |
            11
            17
          distribution: corretto

      - name: Setup and execute Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: build check publish --info --stacktrace --no-configuration-cache -Porg.gradle.java.installations.auto-detect=false -Porg.gradle.java.installations.fromEnv=JAVA_HOME_11_X64,JAVA_HOME_17_X64
